[package]
name = "coop"
version = "0.0.0"
authors = ["Magnus Larsen <golgothasTerror101@gmail.com>"]

[dependencies]
#Graphics
gl = "*"
#Window creation
sdl2 = "*"
#Compute
ocl={git = "https://github.com/cogciprocate/ocl.git" }
